fragment planItem on PlanItem {
  id
  name
  status
  notes
  parent {
    id
  }
  aggregate {
    id
  }
  preparation
  ingredient {
    id
  }
  quantity {
    quantity
    units {
      name
      id
    }
  }
  components {
    id
  }
  bucket {
    id
  }
}
