query recipePhotoUpload($contentType: String!, $originalFilename: String!) {
  profile {
    scratchFile(
      contentType: $contentType
      originalFilename: $originalFilename
    ) {
      url
      filename
      contentType
      cacheControl
    }
  }
}
