import { CodegenConfig } from "@graphql-codegen/cli";

const coreConfig = {
  scalars: {
    Cursor: "string",
    Date: "string",
    DateTime: "string",
    Long: "number",
    NonNegativeFloat: "number",
    NonNegativeInt: "number",
    PositiveInt: "number",
  },
  avoidOptionals: {
    field: true,
    inputValue: false,
  },
  namingConvention: {
    enumValues: "keep",
  },
  inlineFragmentTypes: "mask",
  customDirectives: {
    apolloUnmask: true,
  },
};

const config: CodegenConfig = {
  emitLegacyCommonJSImports: false,
  overwrite: true,
  schema: "./schema.graphql",
  // schema: "http://localhost:8080/graphql",
  documents: ["src/**/*.{ts,tsx}"],
  ignoreNoDocuments: true,
  generates: {
    "./src/__generated__/graphql.ts": {
      plugins: ["typescript"],
      config: {
        ...coreConfig,
        dedupeFragments: true,
        immutableTypes: true,
      },
    },
    "./src/": {
      preset: "near-operation-file",
      plugins: ["typescript-operations", "typed-document-node"],
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: "./__generated__/graphql.ts",
        folder: "__generated__",
      },
      config: {
        ...coreConfig,
        defaultScalarType: "unknown",
        nonOptionalTypename: true,
        skipTypeNameForRoot: true,
      },
    },
  },
};

export default config;
