query getRecipeDetail($id: ID!) {
  library {
    getRecipeById(id: $id) {
      id
      mine
      name
      externalUrl
      yield
      totalTime
      calories
      labels
      sections {
        id
        sectionOf {
          id
        }
      }
      ownedBy {
        id
        ...userAvatar
      }
      photo {
        url
      }
      ...recipePhoto
      ...ingredientsAndDirections
      ...recipeSections
    }
  }
}
