query getRecipeGrid(
  $query: String! = ""
  $scope: LibrarySearchScope! = MINE
  $first: NonNegativeInt! = 12
  $after: Cursor = null
  $activePlanId: ID!
) {
  library {
    recipes(first: $first, query: $query, scope: $scope, after: $after) {
      edges {
        cursor
        node {
          id
          ...recipeCard
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
  ...sendToPlan
}
