query Cook($planId: ID!, $itemId: ID!) {
  planner {
    plan(id: $planId) {
      id
      mine
      grants {
        level
        user {
          id
          me
        }
      }
    }
    planItem(id: $itemId) {
      id
      ...planItem
    }
  }
}
