query Planner {
    planner {
        plans {
            id
            name
            color
            ownedBy {
                id
                ...userAvatar
            }
            buckets {
                id
                date
                name
            }
            notes
            descendants {
                id
                ...planItem
            }
        }
    }
}
