query Planner {
  planner {
    plans {
      id
      name
      color
      ownedBy {
        id
        ...userAvatar
      }
      buckets {
        id
        date
        name
      }
      children {
        id
      }
      notes
      descendants {
        id
        ...timelineItem @unmask
        ...planItem
      }
    }
  }
}
