query Planner {
  planner {
    plans {
      id
      name
      color
      mine
      grants {
        level
        user {
          id
          me
        }
      }
      ownedBy {
        id
        ...userAvatar
      }
      buckets {
        id
        date
        name
      }
      children {
        id
      }
      notes
      descendants {
        id
        # Unmasked so plain JS can build the timeline, before it gets passed
        # to components for rendering.
        ...timelineItem @unmask
        ...planItem
      }
    }
  }
}
