import { type PossibleTypesMap } from "@apollo/client";

/**
 * Generated by 'pnpm run possible-types'.
 */
export const possibleTypes: PossibleTypesMap = {
  AccessControlled: ["Plan"],
  CorePlanItem: ["Plan", "PlanItem"],
  Ingredient: ["PantryItem", "Recipe"],
  Node: [
    "Favorite",
    "Label",
    "PantryItem",
    "Plan",
    "PlanItem",
    "PlannedRecipeHistory",
    "Recipe",
    "Section",
    "UnitOfMeasure",
    "User",
    "UserDevice",
  ],
  Owned: ["Acl", "Plan", "Recipe"],
};
