fragment recipeCard on Recipe {
  id
  name
  labels
  ...cardFavorite
  ownedBy {
    id
    ...userAvatar
  }
  ...cardPhoto
  plannedHistory(last: 1, status: COMPLETED) {
    doneAt
    ratingInt
  }
}
