fragment ingredientsAndDirections on IngredientCollection {
  ingredients {
    raw
    quantity {
      quantity
      units {
        id
        name
      }
    }
    ingredient {
      id
      name
    }
    preparation
  }
  directions
}
