query recognizeIngredient($raw: String!, $cursor: NonNegativeInt!) {
  library {
    recognizeItem(raw: $raw, cursor: $cursor) {
      raw
      cursor
      ranges {
        start
        end
        type
        quantity
        id
      }
    }
  }
}
