query recognizeIngredient(
  $raw: String!
  $cursor: NonNegativeInt!
  $choice: RecognitionChoice
  $suggest: Boolean! = false
) {
  library {
    recognizeItem(raw: $raw, cursor: $cursor, choice: $choice) {
      raw
      cursor
      ranges {
        start
        end
        type
        quantity
        id
      }
      suggestions(grouped: true) @include(if: $suggest) {
        name
        kind
        detail
        target {
          start
          end
          type
          id
        }
      }
    }
  }
}
